name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2.4"
          gleam-version: "1.8.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: gleam deps download
      - run: gleam test --target erlang
      - run: gleam test --target javascript
      - run: gleam format --check src test
